@startuml RAO01

actor "Administrador departamento de achados e perdidos" as admin
participant "Sistema" as sistema

admin -> sistema: Acessa a página de cadastro de usuários
sistema -> admin: Exibe o formulário de cadastro de usuário e local
admin -> sistema: Preenche e submete o formulário
sistema -> sistema: Válida os dados submetidos

group Dados inválidos
  sistema -> admin: Exibe os erros de válidação
end

group Dados válidos
  sistema -> sistema: Realiza o cadastro do local e do usuário no banco de dados
  sistema -> sistema: Realiza o login do usuário recem cadastrado
  sistema -> admin: Redireciona para a página de gerenciamento de objetos
end

@enduml