@startuml RAP02

actor "Administrador departamento de achados e perdidos" as admin
participant "Sistema" as sistema

admin -> sistema: Acessa a página de gerenciamento de objetos
sistema -> sistema: Verifica se o usuário está logado

group Usuário deslogado
  sistema -> admin: Redireciona para a página de login
end

group Usuário logado
  sistema -> admin: Exibe a lista de objetos cadastrados com as opções para edição e exclusão e uma opção de cadastrar objeto
end

@enduml