@startuml RAP05

actor "Administrador departamento de achados e perdidos" as admin
participant "Sistema" as sistema

admin -> sistema: Acessa a página de gerenciamento de objetos
sistema -> sistema: Verifica se o usuário está logado

group Usuário deslogado
  sistema -> admin: Redireciona para a página de login
end

group Usuário logado
  sistema -> admin: Exibe a lista de objetos cadastrados com as opções para edição e exclusão e uma opção de cadastrar objeto
  admin -> sistema: Seleciona a opção para excluir um objeto
  sistema -> admin: Exibe uma mensagem pedindo a confirmação para exclusão
  admin -> sistema: Confirma a exclusão do objeto
  sistema -> sistema: Exclui o objeto do banco de dados
  sistema -> admin: Exibe uma mensagem informando que o objeto foi excluido com sucesso
  sistema -> admin: Redireciona para a página de gerenciamento de objetos
end

@enduml